[tool.poetry]
name = "vaultbot-discord"
version = "2.1.0"
description = "Discord bot for VaultBot"
authors = ["tbrittain <treybrittain@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
alive-progress = "^2.4.0"
discord = "^1.7.3"
python-dotenv = "^0.20.0"
spotipy = "^2.19.0"
pandas = "^1.4.1"
psycopg2 = "^2.9.3"
google-cloud-logging = "^3.0.0"
google-cloud-secret-manager = "^2.9.2"
discord-webhook = "^0.15.0"

[tool.poetry.dev-dependencies]
pylint = "^2.13.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
